### ISSUE TITLE
View post page import file error

### ISSUE THREAD

**Issue by hankkk** [wowafrica/wowafrica#32]
http://wowafrica.tw/view_post_list/posts/styles/main.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://wowafrica.tw/view_post_list/posts/scripts/bundle.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://wowafrica.tw/view_post_list/posts/scripts/vendor.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://wowafrica.tw/view_post_list/posts/scripts/vendor.bundle.js Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by jessy1092** [comment]
I think this is related to #35
