### ISSUE TITLE
RWD

### ISSUE THREAD

**Issue by jessy1092** [wowafrica/wowafrica#7]

**Comment by hankkk** [comment]
Reference
https://developers.google.com/web/fundamentals/layouts/index?hl=en

**Comment by hankkk** [comment]
Google test
https://developers.google.com/webmasters/mobile-sites/get-started/
https://www.google.com/webmasters/tools/mobile-friendly/

**Comment by jessy1092** [comment]
Enable by 1445ddab3bed1fab14acc17b08b367f0b6eac5c8
